export const siteConfig = {
  name: "锤瓜 CUIGUA",
  tagline: "不完美治愈力",
  taglineEn: "The Healing Power of Imperfection",
  description: "Audio Visual Performance Project by Mr.V & VJ Mian",
  label: "谱造司 PUZAOSI",
  
  navigation: [
    { name: "首页", nameEn: "Home", href: "/" },
    { name: "关于", nameEn: "About", href: "/#about" },
    { name: "成员", nameEn: "Members", href: "/#members" },
    { name: "体验", nameEn: "Experience", href: "/#experience" },
    { name: "画廊", nameEn: "Gallery", href: "/#gallery" },
    { name: "联系", nameEn: "Contact", href: "/#contact" },
  ],

  hero: {
    badge: "Audio Visual Performance",
    title: "锤瓜",
    titleEn: "CUIGUA",
    subtitle: "囧恩的神经漫游记",
    subtitleEn: "Jon's Neuron Odyssey",
    description: "献给 Kidult 群体的沉浸式视听绘本",
    descriptionEn: "An immersive audio-visual picture book for the Kidult",
  },

  about: {
    title: "关于项目",
    titleEn: "About",
    philosophy: {
      title: "核心理念",
      titleEn: "Philosophy",
      text: "聚焦于\"不完美治愈力\"这一内核，通过接纳个体的笨拙、脆弱与怪癖，在感官的震荡中完成一场关于自我意识的\"漫游\"。",
      textEn: "Centered on the \"Healing Power of Imperfection,\" we embrace clumsiness, vulnerability, and quirks — completing a journey of self-consciousness through sensory tremors.",
    },
    concept: {
      title: "通感漫游",
      titleEn: "Synesthetic Odyssey",
      text: "声音与影像深度缠绕，将原创 IP《囧恩的神经漫游记》转化为一部沉浸式视听体验。",
      textEn: "Deeply intertwined sound and visuals transform our original IP \"Jon's Neuron Odyssey\" into an immersive audio-visual experience.",
    },
  },

  members: [
    {
      id: "mr-v",
      name: "Mr.V",
      role: "声音艺术",
      roleEn: "Sound Artist",
      description: "声音艺术家，声音设计探索者。专注于 Techno、Experimental Electronic、Ambient、Downtempo、IDM 等声音风格的创作与研究。通过声音构建情绪空间，与视觉艺术家 VJ Mian 共同驱动锤瓜的视听艺术现场。",
      descriptionEn: "Sound artist exploring sound design. Focused on Techno, Experimental Electronic, Ambient, Downtempo, and IDM. Building emotional spaces through sound.",
      accent: "orange",
    },
    {
      id: "vj-mian",
      name: "VJ Mian",
      role: "视觉艺术",
      roleEn: "Visual Artist",
      description: "视觉艺术家，实时影像表演者。创造跳舞的囧恩、迷宫头、无脸怪兽等视觉意象，通过波普超现实主义与怪诞美学的融合，构建一个献给成人童心群体的视觉宇宙。",
      descriptionEn: "Visual artist and real-time video performer. Creating visual imagery like Dancing Jon, Maze Head, and Faceless Monster through Pop-Surrealism.",
      accent: "purple",
    },
  ],

  experience: {
    title: "通感漫游",
    titleEn: "Synesthetic Odyssey",
    description: "在节点间漫游，探索声音与视觉的无限连接",
    descriptionEn: "Wander between nodes, explore infinite connections between sound and vision",
    nodes: [
      {
        id: "jon",
        type: "jon",
        label: "囧恩",
        labelEn: "Dancing Jon",
        description: "节奏律动中展现笨拙而治愈的生命力",
        descriptionEn: "笨拙中展现的生命力，在节奏中跳舞的囧恩",
        category: "character",
      },
      {
        id: "maze-head",
        type: "mazeHead",
        label: "迷宫头",
        labelEn: "Maze Head",
        description: "无限延伸的意识迷宫，象征思考的困局与突破",
        descriptionEn: "Infinite consciousness maze, symbolizing the dilemma and breakthrough of thinking",
        category: "character",
      },
      {
        id: "faceless",
        type: "faceless",
        label: "无脸怪兽",
        labelEn: "Faceless Monster",
        description: "剥离具象特征的情绪载体，先锋怪诞的超现实美感",
        descriptionEn: "Emotion vessel stripped of concrete features, avant-garde grotesque surreal beauty",
        category: "character",
      },
      {
        id: "techno",
        type: "sound",
        label: "Techno",
        description: "强劲节拍驱动身体震动",
        descriptionEn: "Pulsing rhythms that move your body",
        category: "sound",
      },
      {
        id: "ambient",
        type: "sound",
        label: "Ambient",
        description: "氛围音景包裹沉浸体验",
        descriptionEn: "Atmospheric soundscapes for immersion",
        category: "sound",
      },
      {
        id: "downtempo",
        type: "sound",
        label: "Downtempo",
        description: "慵懒节拍放松神经",
        descriptionEn: "Lazy beats to relax your nerves",
        category: "sound",
      },
      {
        id: "idm",
        type: "sound",
        label: "IDM",
        description: "智能舞曲的解构与重塑",
        descriptionEn: "Deconstruction of intelligent dance music",
        category: "sound",
      },
    ],
    edges: [
      { source: "jon", target: "maze-head", label: "意识流" },
      { source: "maze-head", target: "faceless", label: "情绪释放" },
      { source: "jon", target: "techno", label: "节奏驱动" },
      { source: "ambient", target: "maze-head", label: "氛围渗透" },
      { source: "downtempo", target: "faceless", label: "情感共鸣" },
      { source: "techno", target: "faceless", label: "力量传递" },
      { source: "idm", target: "jon", label: "实验探索" },
    ],
  },

  gallery: {
    title: "画廊",
    titleEn: "Gallery",
    description: "演出瞬间 / Performance Moments",
    items: [
      { id: 1, title: "现场演出", titleEn: "Live Performance", category: "show" },
      { id: 2, title: "视觉装置", titleEn: "Visual Installation", category: "installation" },
      { id: 3, title: "幕后花絮", titleEn: "Behind the Scenes", category: "behind" },
      { id: 4, title: "囧恩动画", titleEn: "Jon Animation", category: "animation" },
      { id: 5, title: "演出海报", titleEn: "Show Posters", category: "poster" },
      { id: 6, title: "周边产品", titleEn: "Merchandise", category: "merch" },
    ],
  },

  contact: {
    title: "联系",
    titleEn: "Contact",
    description: "演出邀约 / Booking Inquiries",
    email: "contact@cuigua.art",
    social: [
      { name: "Instagram", url: "https://instagram.com/cuigua", icon: "Instagram" },
      { name: "微博", url: "https://weibo.com/cuigua", icon: "Globe" },
      { name: "哔哩哔哩", url: "https://bilibili.com/cuigua", icon: "Video" },
    ],
  },

  footer: {
    label: "谱造司 PUZAOSI",
    copyright: "© 2024 锤瓜 CUIGUA. All rights reserved.",
  },
};
